name: PEP-8 Style Check
run-name: PEP-8 Style Check Underway
on: [push]
jobs:
  CheckStyle:
    runs-on: ubuntu-latest
    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
