name: PEP-8 Style Check
run-name: PEP-8 Style Check Underway
on: [push]
jobs:
  CheckStyle:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
